export const STATIC_REPLIES: { keywords: string[]; reply: string }[] = [
  { keywords: ['bonjour'], reply: "Bonjour ! Je suis l'assistant CreditPro Tunisie. En quoi puis-je vous aider ?" },
  { keywords: ['bonsoir'], reply: "Bonsoir ! Je suis l'assistant CreditPro. Posez-moi vos questions sur le crédit en TND, le dossier ou le suivi." },
  { keywords: ['bonne nuit', 'bonne soirée'], reply: 'Bonne soirée ! Revenez quand vous voulez pour des infos sur CreditPro Tunisie.' },
  { keywords: ['salut'], reply: 'Salut ! Comment puis-je vous aider ? Je peux vous renseigner sur les crédits en TND, le dépôt de dossier ou le suivi.' },
  { keywords: ['coucou'], reply: 'Coucou ! Je suis là pour vous. Quelle est votre question sur CreditPro ?' },
  { keywords: ['hello'], reply: 'Hello ! Bienvenue sur CreditPro Tunisie. Comment puis-je vous aider ?' },
  { keywords: ['hi '], reply: "Hi ! En quoi puis-je vous aider pour votre crédit en TND ?" },
  { keywords: ['hey '], reply: 'Hey ! Posez-moi vos questions sur CreditPro (dossier, suivi, simulateur).' },
  { keywords: ['bon matin', 'good morning'], reply: "Bonjour ! Je suis l'assistant CreditPro. Quelle question avez-vous ?" },
  { keywords: ['bonne après-midi', 'good afternoon'], reply: "Bonjour ! En quoi puis-je vous aider pour votre projet de crédit en TND ?" },
  { keywords: ['ça va', 'comment ça va', 'comment vas-tu', 'comment allez-vous'], reply: "Très bien, merci ! Et vous ? N'hésitez pas à me poser vos questions sur CreditPro (crédit TND, dossier, suivi)." },
  { keywords: ['qui es-tu', 'qui êtes-vous', 'tu es qui'], reply: "Je suis l'assistant virtuel de CreditPro Tunisie. Je réponds aux questions sur les crédits en TND, le dépôt de dossier et le suivi." },
  { keywords: ['tu fais quoi', 'vous faites quoi', 'quoi de neuf'], reply: 'Je suis là pour vous aider sur CreditPro : crédit en TND, simulateur, dépôt de dossier, suivi. Quelle est votre question ?' },
  { keywords: ['oui'], reply: "D'accord. Avez-vous une question précise sur le crédit, le dossier ou le suivi ?" },
  { keywords: ['non'], reply: "Pas de souci. Si vous changez d'avis, posez-moi une question sur CreditPro." },
  { keywords: ['merci', 'merci beaucoup', 'thanks', 'thank you'], reply: "Avec plaisir ! N'hésitez pas si vous avez d'autres questions. Bonne journée." },
  { keywords: ['ok', 'd\'accord', 'parfait', 'super', 'très bien', 'compris'], reply: 'Parfait ! Autre chose ? Je peux vous aider sur le crédit, le dossier ou le suivi.' },
  { keywords: ['s\'il te plaît', 's\'il vous plaît', 'please', 'stp', 'svp'], reply: 'Bien sûr ! Dites-moi ce dont vous avez besoin (infos crédit, contact, dépôt de dossier, suivi).' },
  { keywords: ['au revoir', 'bye', 'à bientôt', 'à plus', 'ciao', 'adieu'], reply: 'Au revoir ! Revenez quand vous voulez. Bonne journée.' },
  { keywords: ['bonne journée', 'bonne journee'], reply: "Merci, à vous aussi ! N'hésitez pas à revenir pour toute question sur CreditPro." },
  { keywords: ['humain', 'robot', 'bot', 'machine'], reply: "Je suis l'assistant automatique de CreditPro. Pour un conseiller : contact@creditpro.tn ou +216 70 000 000." },
  { keywords: ['menu', 'options', 'que peux-tu faire', 'liste'], reply: 'Je peux vous aider sur : contact (email, tél), suivi de dossier, simulateur, dépôt de demande, documents, délais, types de crédit, score, garanties. Posez une question !' },
  { keywords: ['contact', 'téléphone', 'email', 'support', 'joindre', 'contacter', 'appeler'], reply: 'Pour nous contacter :\n• E-mail : contact@creditpro.tn\n• Téléphone : +216 70 000 000' },
  { keywords: ['suivi', 'suivre', 'dossier', 'numéro', 'tracking', 'code', 'où en est', 'statut'], reply: "Pour suivre votre dossier sans vous connecter : page d'accueil → section « Suivi de mon crédit » → entrez le numéro de dossier (8 caractères). Vous verrez le statut en temps réel." },
  { keywords: ['simulateur', 'simulation', 'mensualité', 'montant', 'estimer', 'calculer'], reply: "Simulateur : en page d'accueil cliquez sur « Simulateur de crédit » (ou /client/simulator). Vous estimez les mensualités et le montant empruntable en TND." },
  { keywords: ['dépôt', 'déposer', 'demande', 'créer un compte', 'inscription', 'formulaire', 'nouvelle demande'], reply: 'Pour déposer une demande : 1) Créez un compte, 2) Connectez-vous, 3) « Nouvelle demande » et remplissez le formulaire guidé. Réponse préliminaire en quelques minutes.' },
  { keywords: ['document', 'pièce', 'cin', 'bulletin', 'justificatif', 'téléverser', 'upload'], reply: 'Pièces à fournir : CIN (recto/verso), bulletins de salaire (3 derniers mois), relevés bancaires (6 mois), justificatif de domicile. PDF ou image.' },
  { keywords: ['délai', 'décision', 'combien de temps', 'réponse', 'instruction', 'traiter'], reply: "Réponse préliminaire en quelques minutes. Instruction complète : quelques jours ouvrés. Suivez l'avancement dans « Suivi de mon crédit »." },
  { keywords: ['tnd', 'dinars', 'devise', 'monnaie'], reply: 'Tous nos crédits sont en dinars tunisiens (TND). Montants et mensualités en TND. Réservé aux résidents en Tunisie.' },
  { keywords: ['score', 'scoring', 'évaluation', 'refus', 'accepté', 'approuvé'], reply: "Chaque dossier reçoit un score (situation pro, revenus, capacité d'endettement). Il guide la décision : favorable, compléments ou refus. Votre score est visible sur la fiche demande." },
  { keywords: ['garantie', 'garanties requises'], reply: 'Si des garanties sont demandées, les détails apparaissent dans le suivi de dossier. Types : immobilier, véhicule, virement de salaire, caution. Contact : contact@creditpro.tn pour le détail.' },
  { keywords: ['type', 'types', 'crédit conso', 'consommation', 'immobilier', 'auto', 'véhicule'], reply: 'Nous proposons du crédit à la consommation et du crédit immobilier, tout en TND. Le formulaire de demande précise l\'objet (achat immobilier, véhicule, travaux, etc.).' },
  { keywords: ['éligible', 'éligibilité', 'conditions', 'qui peut', 'réservé'], reply: 'Réservé aux résidents en Tunisie. Il faut avoir au moins 21 ans, un revenu et des pièces d\'identité (CIN). Le score évalue ensuite votre dossier.' },
  { keywords: ['âge', 'minimum', 'mineur'], reply: "L'âge minimum pour déposer une demande est 21 ans (pratique courante en Tunisie)." },
  { keywords: ['revenu', 'revenus', 'salaire', 'minimum'], reply: "Vos revenus (salaire, autres revenus) sont demandés dans le formulaire. Ils servent au calcul du score et du taux d'endettement. Un revenu minimum peut s'appliquer ; le simulateur vous aide à vous situer." },
  { keywords: ['taux', 'intérêt', 'taeg', 'taux d\'intérêt'], reply: 'Les taux et conditions précises dépendent de votre dossier et du type de crédit. Utilisez le simulateur pour une estimation, puis contact@creditpro.tn ou +216 70 000 000 pour une offre personnalisée.' },
  { keywords: ['durée', 'mois', 'années', 'remboursement'], reply: 'La durée du crédit (en mois) est choisie dans la demande (généralement entre 12 et 300 mois selon le type). Le simulateur affiche les mensualités selon la durée.' },
  { keywords: ['étape', 'étapes', 'comment ça marche', 'processus'], reply: '1) Créer un compte 2) Remplir le dossier en ligne 3) Analyse et score 4) Réponse (préliminaire puis instruction). Vous suivez tout dans « Suivi de mon crédit ».' },
  { keywords: ['modifier', 'changer', 'éditer', 'corriger ma demande'], reply: 'Une demande « en attente » peut être modifiée ou supprimée depuis « Mes demandes » : lien « Modifier » ou « Supprimer » sur la ligne du dossier.' },
  { keywords: ['supprimer', 'annuler', 'retirer ma demande'], reply: 'Seules les demandes en attente peuvent être supprimées. Allez dans « Mes demandes » puis « Supprimer » sur le dossier concerné.' },
  { keywords: ['pdf', 'récapitulatif', 'télécharger', 'imprimer'], reply: 'Sur la page de détail de votre demande, utilisez « Télécharger le récapitulatif (PDF) » pour obtenir un résumé du dossier.' },
  { keywords: ['connexion', 'connecter', 'login', 'se connecter'], reply: 'Cliquez sur « Connexion » en haut à droite, puis entrez votre e-mail et mot de passe. Si vous n\'avez pas de compte, « Créer un compte » d\'abord.' },
  { keywords: ['mot de passe', 'oublié', 'réinitialiser'], reply: 'En cas de mot de passe oublié, contactez le support : contact@creditpro.tn ou +216 70 000 000 pour réinitialiser l\'accès.' },
  { keywords: ['tunisie', 'résident', 'tunisien'], reply: 'CreditPro Tunisie est réservé aux résidents en Tunisie. Tous les montants sont en dinars tunisiens (TND).' },
  { keywords: ['sécurité', 'données', 'protéger', 'confidentialité'], reply: 'Vos données sont traitées de manière sécurisée (chiffrement, bonnes pratiques). Conformité aux usages du secteur et à la réglementation (BCT).' },
  { keywords: ['bct', 'réglementation', 'banque'], reply: 'Nous nous inscrivons dans le cadre des pratiques du secteur en Tunisie et des recommandations de la BCT. Pour les détails réglementaires, contact@creditpro.tn.' },
  { keywords: ['aide', 'help', 'question', 'faq'], reply: 'Vous pouvez parcourir les sections « Comment ça marche » et « Fonctionnalités » sur le site, utiliser le simulateur, ou nous écrire : contact@creditpro.tn / +216 70 000 000.' },
];
